version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "443:443"
        volumes:
            - .:/code
            - ./docker/site-ssl.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt/archive/meta.pla.net.ar:/certs
        networks:
            - code-network
    app:
        image: php:7.4-cli
        volumes:
            - .:/code
        networks:
            - code-network
        entrypoint: ["php", "-S", "0.0.0.0:9000", "/code/index.php"]

networks:
    code-network:
        driver: bridge
