version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "9400:80"
        volumes:
            - .:/code
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - .:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
